// <auto-generated />
namespace BacklogMaintainer.ViewModel
{
	using System;
	using System.Windows;
	using System.Windows.Controls;
	using System.ComponentModel;

	/// <summary>
	/// このクラスはMainWindowViewModelクラスの定義によって、自動生成されました。
	/// このファイルをエディタで直接編集しないでください。
	/// </summary>
	public partial class MainWindowViewModel
	{
#region 処理中表示
		/// <summary>
		/// 処理中表示
		/// </summary>
		private bool _isBusy;
		public bool IsBusy
		{
			get { return this._isBusy; }
			set 
			{ 
				if ( this._isBusy == value ) {
					return;
				}
				this._isBusy = value; 
				
				this.RaisePropertyChanged(() => this.IsBusy);
			}
		}
#endregion
#region ユーザー数
		/// <summary>
		/// ユーザー数
		/// </summary>
		private int _userCount;
		public int UserCount
		{
			get { return this._userCount; }
			set 
			{ 
				if ( this._userCount == value ) {
					return;
				}
				this._userCount = value; 
				
				this.RaisePropertyChanged(() => this.UserCount);
			}
		}
#endregion
#region グループ数
		/// <summary>
		/// グループ数
		/// </summary>
		private int _groupCount;
		public int GroupCount
		{
			get { return this._groupCount; }
			set 
			{ 
				if ( this._groupCount == value ) {
					return;
				}
				this._groupCount = value; 
				
				this.RaisePropertyChanged(() => this.GroupCount);
			}
		}
#endregion
#region プロジェクト数
		/// <summary>
		/// プロジェクト数
		/// </summary>
		private int _projectCount;
		public int ProjectCount
		{
			get { return this._projectCount; }
			set 
			{ 
				if ( this._projectCount == value ) {
					return;
				}
				this._projectCount = value; 
				
				this.RaisePropertyChanged(() => this.ProjectCount);
			}
		}
#endregion
#region 非アーカイブプロジェクト数
		/// <summary>
		/// 非アーカイブプロジェクト数
		/// </summary>
		private int _activeProjectCount;
		public int ActiveProjectCount
		{
			get { return this._activeProjectCount; }
			set 
			{ 
				if ( this._activeProjectCount == value ) {
					return;
				}
				this._activeProjectCount = value; 
				
				this.RaisePropertyChanged(() => this.ActiveProjectCount);
			}
		}
#endregion
#region タブ選択変更
		/// <summary>
		/// タブ選択変更
		/// </summary>
		private Livet.Commands.ListenerCommand<System.Windows.Controls.SelectionChangedEventArgs> _selectionChangedCommand;

		public Livet.Commands.ListenerCommand<System.Windows.Controls.SelectionChangedEventArgs> SelectionChangedCommand
		{
			get
			{
				if (this._selectionChangedCommand == null)
				{
					this._selectionChangedCommand = new Livet.Commands.ListenerCommand<System.Windows.Controls.SelectionChangedEventArgs>(this.SelectionChanged);
				}
				return this._selectionChangedCommand;
			}
		}
		//private void SelectionChanged(System.Windows.Controls.SelectionChangedEventArgs message) {}
#endregion
	}
}
