// <auto-generated />
namespace BacklogMaintainer.ViewModel
{
	using System;
	using System.Windows;
	using System.Windows.Controls;
	using System.ComponentModel;

	/// <summary>
	/// このクラスはMainWindowViewModelクラスの定義によって、自動生成されました。
	/// このファイルをエディタで直接編集しないでください。
	/// </summary>
	public partial class MainWindowViewModel
	{
#region 処理中表示
		/// <summary>
		/// 処理中表示
		/// </summary>
		private bool _isBusy;
		public bool IsBusy
		{
			get { return this._isBusy; }
			set 
			{ 
				if ( this._isBusy == value ) {
					return;
				}
				this._isBusy = value; 
				
				this.RaisePropertyChanged(() => this.IsBusy);
			}
		}
#endregion
#region 全ユーザー数
		/// <summary>
		/// 全ユーザー数
		/// </summary>
		private int _userCount;
		public int UserCount
		{
			get { return this._userCount; }
			set 
			{ 
				if ( this._userCount == value ) {
					return;
				}
				this._userCount = value; 
				
				this.RaisePropertyChanged(() => this.UserCount);
			}
		}
#endregion
#region 全グループ数
		/// <summary>
		/// 全グループ数
		/// </summary>
		private int _groupCount;
		public int GroupCount
		{
			get { return this._groupCount; }
			set 
			{ 
				if ( this._groupCount == value ) {
					return;
				}
				this._groupCount = value; 
				
				this.RaisePropertyChanged(() => this.GroupCount);
			}
		}
#endregion
	}
}
