// <auto-generated />
namespace BacklogMaintainer.ViewModel
{
	using System;
	using System.Windows;
	using System.Windows.Controls;
	using System.ComponentModel;

	/// <summary>
	/// このクラスはMainWindowViewModelクラスの定義によって、自動生成されました。
	/// このファイルをエディタで直接編集しないでください。
	/// </summary>
	public partial class MainWindowViewModel
	{
#region 処理中表示
		/// <summary>
		/// 処理中表示
		/// </summary>
		private bool _isBusy;
		public bool IsBusy
		{
			get { return this._isBusy; }
			set 
			{ 
				if ( this._isBusy == value ) {
					return;
				}
				this._isBusy = value; 
				
				this.RaisePropertyChanged(() => this.IsBusy);
			}
		}
#endregion
	}
}
